version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    commit-message:
      prefix: build
      include: scope
    schedule:
      interval: "weekly"
    groups:
      non-major:
        update-types:
          - "minor"
          - "patch"
